import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Send, Loader2, Mail, Settings } from "lucide-react";
import { toast } from "sonner";

const SMTP_STORAGE_KEY = "net2app_smtp_config";

function loadSmtp() {
  try { return JSON.parse(localStorage.getItem(SMTP_STORAGE_KEY) || "{}"); } catch (_) { return {}; }
}
function saveSmtp(cfg) {
  localStorage.setItem(SMTP_STORAGE_KEY, JSON.stringify(cfg));
}

function buildRateTableHtml(rates, entityName, note) {
  const rows = rates.map(r => `
    <tr>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;">${r.country || '-'}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;">${r.network || '-'}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;font-family:monospace;">${r.mcc || '-'}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;font-family:monospace;">${r.mnc || '-'}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;font-family:monospace;">${r.prefix || '-'}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;font-weight:bold;color:#16a34a;">${r.rate?.toFixed(5) || '0.00000'}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0;">${r.currency || 'USD'}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:Inter,Arial,sans-serif;color:#1e293b;max-width:900px;margin:0 auto;padding:24px;">
  <div style="background:#1d4ed8;color:white;padding:16px 20px;border-radius:8px 8px 0 0;">
    <h2 style="margin:0;font-size:18px;">Rate Card Update</h2>
    <p style="margin:4px 0 0;font-size:13px;opacity:0.85;">Net2app Platform — ${new Date().toLocaleDateString()}</p>
  </div>
  <div style="border:1px solid #e2e8f0;border-top:none;padding:20px;border-radius:0 0 8px 8px;">
    <p style="margin-top:0;">For: <strong>${entityName}</strong></p>
    ${note ? `<p style="background:#f0f9ff;border-left:3px solid #3b82f6;padding:10px 14px;border-radius:4px;font-size:13px;">${note}</p>` : ''}
    <p style="color:#64748b;font-size:13px;">This rate card supersedes all previous versions. Please update your systems accordingly.</p>
    <table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:16px;">
      <thead>
        <tr style="background:#1d4ed8;color:white;">
          <th style="padding:8px 10px;text-align:left;">Country</th>
          <th style="padding:8px 10px;text-align:left;">Network</th>
          <th style="padding:8px 10px;text-align:left;">MCC</th>
          <th style="padding:8px 10px;text-align:left;">MNC</th>
          <th style="padding:8px 10px;text-align:left;">Prefix</th>
          <th style="padding:8px 10px;text-align:left;">Rate</th>
          <th style="padding:8px 10px;text-align:left;">Currency</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
    <p style="margin-top:20px;font-size:12px;color:#94a3b8;">Total destinations: ${rates.length} | Generated by Net2app</p>
  </div>
</body></html>`;
}

export default function RateEmailDialog({ open, onClose, entityName, entityEmail, rates, entityType }) {
  const savedSmtp = loadSmtp();

  const [toEmail, setToEmail] = useState(entityEmail || '');
  const [subject, setSubject] = useState(`Rate Card Update — ${entityName} — ${new Date().toLocaleDateString()}`);
  const [note, setNote] = useState('');
  const [loading, setLoading] = useState(false);
  const [smtpMode, setSmtpMode] = useState(savedSmtp.host ? 'custom' : 'platform');

  // Custom SMTP state
  const [smtp, setSmtp] = useState({
    host: savedSmtp.host || '',
    port: savedSmtp.port || '587',
    user: savedSmtp.user || '',
    pass: savedSmtp.pass || '',
    from: savedSmtp.from || '',
  });

  const setS = (k, v) => setSmtp(p => ({ ...p, [k]: v }));

  const handleSend = async () => {
    if (!toEmail) { toast.error("Recipient email required"); return; }
    setLoading(true);
    const htmlBody = buildRateTableHtml(rates, entityName, note);

    try {
      if (smtpMode === 'custom') {
        if (!smtp.host || !smtp.user || !smtp.pass) { toast.error("SMTP host, username and password are required"); setLoading(false); return; }
        // Save SMTP config for next time
        saveSmtp({ host: smtp.host, port: smtp.port, user: smtp.user, from: smtp.from });

        const res = await base44.functions.invoke('sendRateCardSmtp', {
          smtp_host: smtp.host,
          smtp_port: parseInt(smtp.port) || 587,
          smtp_user: smtp.user,
          smtp_pass: smtp.pass,
          smtp_from: smtp.from || smtp.user,
          to: toEmail,
          subject,
          html_body: htmlBody,
        });
        if (res.data?.error) throw new Error(res.data.error);
        toast.success(`Rate card sent via custom SMTP to ${toEmail} (msg ID: ${res.data?.messageId || '—'})`);
      } else {
        // Platform built-in email
        await base44.integrations.Core.SendEmail({ to: toEmail, subject, body: htmlBody });
        toast.success(`Rate card sent to ${toEmail}`);
      }
      onClose();
    } catch (err) {
      toast.error("Send failed: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  const activeRates = rates.filter(r => r.status === 'active');

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Mail className="w-4 h-4" />Send Rate Card — {entityName}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="flex items-center gap-2 p-2 bg-blue-50 border border-blue-200 rounded text-xs text-blue-800">
            <Badge variant="outline" className="bg-blue-100 text-blue-700">{activeRates.length} active rates</Badge>
            <span>({entityType === 'client' ? 'Client' : 'Supplier'} rate card)</span>
          </div>

          <div className="space-y-1.5">
            <Label>Recipient Email(s) * <span className="text-muted-foreground font-normal">(comma-separated)</span></Label>
            <Input type="email" value={toEmail} onChange={e => setToEmail(e.target.value)} placeholder="client@company.com, billing@company.com" />
          </div>

          <div className="space-y-1.5">
            <Label>Subject</Label>
            <Input value={subject} onChange={e => setSubject(e.target.value)} />
          </div>

          <div className="space-y-1.5">
            <Label>Optional Note</Label>
            <Textarea value={note} onChange={e => setNote(e.target.value)} rows={2} placeholder="Please review the updated rates effective from..." />
          </div>

          {/* SMTP Mode */}
          <Tabs value={smtpMode} onValueChange={setSmtpMode}>
            <TabsList className="w-full">
              <TabsTrigger value="platform" className="flex-1 text-xs">Platform Email</TabsTrigger>
              <TabsTrigger value="custom" className="flex-1 text-xs gap-1"><Settings className="w-3 h-3" />Custom SMTP</TabsTrigger>
            </TabsList>

            <TabsContent value="platform" className="mt-3">
              <div className="p-3 bg-muted/40 rounded-lg text-xs text-muted-foreground">
                Sends via the Net2app platform email — no configuration needed. Email will be sent from the platform's default address.
              </div>
            </TabsContent>

            <TabsContent value="custom" className="mt-3 space-y-3">
              <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-800">
                Use your own SMTP server (Gmail, Outlook, SendGrid, etc.). Settings are saved locally in your browser.
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="col-span-2 space-y-1">
                  <Label className="text-xs">SMTP Host *</Label>
                  <Input className="h-8 text-xs" value={smtp.host} onChange={e => setS('host', e.target.value)} placeholder="smtp.gmail.com" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">Port</Label>
                  <Input className="h-8 text-xs" value={smtp.port} onChange={e => setS('port', e.target.value)} placeholder="587" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">From Name/Email</Label>
                  <Input className="h-8 text-xs" value={smtp.from} onChange={e => setS('from', e.target.value)} placeholder="Net2app <admin@company.com>" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">Username *</Label>
                  <Input className="h-8 text-xs" value={smtp.user} onChange={e => setS('user', e.target.value)} placeholder="admin@company.com" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs">Password *</Label>
                  <Input type="password" className="h-8 text-xs" value={smtp.pass} onChange={e => setS('pass', e.target.value)} placeholder="App password / API key" />
                </div>
              </div>
              <p className="text-xs text-muted-foreground">For Gmail: use an App Password (not your regular password). Port 587 = STARTTLS, 465 = SSL.</p>
            </TabsContent>
          </Tabs>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>Cancel</Button>
          <Button onClick={handleSend} disabled={loading} className="gap-1">
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
            Send Rate Card
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}