// Bash auto-detection script stored as a plain string
// Avoids JS template literal conflicts with bash ${VAR#pattern} syntax
const lines = [
  '#!/bin/bash',
  '# Net2app Server Auto-Detection Script — Debian 12',
  '# Usage: sudo bash detect.sh',
  '',
  'IP=$(hostname -I | awk "{print \\$1}")',
  'HOST=$(hostname -f)',
  'OS=$(lsb_release -d 2>/dev/null | cut -f2)',
  'CPU=$(lscpu | grep "Model name" | cut -d: -f2 | xargs)',
  'RAM=$(free -g | awk "/^Mem:/{print \\$2}")',
  'DISK=$(df -BG / | awk "NR==2{print int(\\$2)}")',
  'AST=$(asterisk -V 2>/dev/null | awk "{print \\$2}" || echo "not installed")',
  'KNL=$(dpkg -l kannel 2>/dev/null | awk "/^ii/{print \\$3}" || echo "not installed")',
  'MDB=$(mysql --version 2>/dev/null | awk "{print \\$5}" | tr -d "," || echo "not installed")',
  '',
  'SVCS=""',
  'systemctl is-active asterisk &>/dev/null && SVCS="asterisk"',
  'systemctl is-active kannel &>/dev/null && SVCS="${SVCS:+${SVCS},}kannel"',
  'systemctl is-active mariadb &>/dev/null && SVCS="${SVCS:+${SVCS},}mariadb"',
  '',
  'SIP_PORT=$(ss -lnup | grep -q ":5060" && echo 5060 || echo 0)',
  'AMI_PORT=$(ss -lntp | grep -q ":5038" && echo 5038 || echo 0)',
  'SMPP_PORT=$(ss -lntp | grep -q ":2775" && echo 2775 || echo 0)',
  'KNLP=$(ss -lntp | grep -q ":13013" && echo 13013 || echo 0)',
  'DBP=$(ss -lntp | grep -q ":3306" && echo 3306 || echo 0)',
  '',
  'echo "{"',
  'echo "  \\"server_ip\\": \\"$IP\\","',
  'echo "  \\"hostname\\": \\"$HOST\\","',
  'echo "  \\"os\\": \\"$OS\\","',
  'echo "  \\"cpu\\": \\"$CPU\\","',
  'echo "  \\"ram_gb\\": $RAM,"',
  'echo "  \\"disk_gb\\": $DISK,"',
  'echo "  \\"asterisk_version\\": \\"$AST\\","',
  'echo "  \\"kannel_version\\": \\"$KNL\\","',
  'echo "  \\"mariadb_version\\": \\"$MDB\\","',
  'echo "  \\"sip_port\\": $SIP_PORT,"',
  'echo "  \\"ami_port\\": $AMI_PORT,"',
  'echo "  \\"smpp_port\\": $SMPP_PORT,"',
  'echo "  \\"kannel_port\\": $KNLP,"',
  'echo "  \\"db_port\\": $DBP,"',
  'echo "  \\"services\\": \\"$SVCS\\""',
  'echo "}"',
];

export const detectScript = lines.join('\n');