import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Copy, Server, MessageSquare, Phone, Database, ShieldCheck } from "lucide-react";
import { toast } from "sonner";

const CodeBlock = ({ code, label }) => (
  <div className="relative">
    {label && <p className="text-xs text-muted-foreground mb-1 font-medium">{label}</p>}
    <div className="bg-gray-900 text-green-400 rounded-lg p-4 font-mono text-xs overflow-x-auto">
      <pre className="whitespace-pre-wrap">{code}</pre>
    </div>
    <Button size="sm" variant="ghost" className="absolute top-6 right-2 h-7 text-gray-400 hover:text-white"
      onClick={() => { navigator.clipboard.writeText(code); toast.success("Copied!"); }}>
      <Copy className="w-3 h-3" />
    </Button>
  </div>
);

const ASTERISK_INSTALL = `#!/bin/bash
# Asterisk 20 on Debian 12 — Net2app Deployment
apt-get update && apt-get upgrade -y
apt-get install -y build-essential wget curl git libssl-dev libncurses5-dev \\
  libnewt-dev libxml2-dev libsqlite3-dev uuid-dev libjansson-dev \\
  mariadb-server mariadb-client libmysqlclient-dev

# Download Asterisk 20
cd /usr/src
wget http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-20-current.tar.gz
tar xvzf asterisk-20-current.tar.gz && cd asterisk-20*/

# Install dependencies
contrib/scripts/install_prereq install

# Configure with MySQL support
./configure --with-jansson-bundled
make menuselect  # enable: res_config_mysql, chan_sip, chan_pjsip, app_agi

make -j$(nproc) && make install && make samples && make config

# Start Asterisk
systemctl enable asterisk && systemctl start asterisk
asterisk -rvv   # connect to CLI`;

const KANNEL_INSTALL = `#!/bin/bash
# Kannel SMS Gateway on Debian 12
apt-get install -y kannel kannel-dev

# Configure Kannel
cat > /etc/kannel/kannel.conf << 'EOF'
group = core
admin-port = 13000
admin-password = YourAdminPass
status-password = YourStatusPass
log-file = "/var/log/kannel/bearerbox.log"
log-level = 0

group = bearerbox-status
status = true

group = smsbox
smsbox-id = net2app-smsbox
bearerbox-host = localhost
sendsms-port = 13013
sendsms-chars = "0123456789+-"
log-file = "/var/log/kannel/smsbox.log"
log-level = 0

# Add your SMSC connections here:
group = smsc
smsc = smpp
smsc-id = supplier1
host = SUPPLIER_HOST
port = SUPPLIER_PORT
smsc-username = USERNAME
smsc-password = PASSWORD
EOF

systemctl enable kannel && systemctl start kannel
# Test: curl "http://localhost:13013/cgi-bin/sendsms?user=admin&pass=YourPass&to=+1234&text=Hello"`;

const SMPP_SETUP = `#!/bin/bash
# SMPP Server (Jasmin/SMPPSim on Debian 12)
# Option 1: Jasmin SMPP Gateway (production)
apt-get install -y python3-pip python3-dev rabbitmq-server redis-server
pip3 install jasmin

# Start Jasmin
jasmin-daemon --install  # Install as systemd service
systemctl enable jasmin && systemctl start jasmin

# Connect Jasmin to Kannel for SMS routing
# In Jasmin CLI:
# smppccm -a  (add SMPP client connector to upstream)
# smppsm -a  (add SMPP server listener for client connections)

# Option 2: Simple SMPP Server config
# Kannel acts as SMPP server natively:
# Add to kannel.conf:
group = smsc
smsc = smpp-server  
port = 2775
system-id = net2app
password = net2apppass`;

const DB_SETUP = `#!/bin/bash
# MariaDB setup for Asterisk + Net2app on Debian 12
mysql -u root << 'EOF'
CREATE DATABASE asterisk CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE DATABASE net2app CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'asterisk'@'localhost' IDENTIFIED BY 'AsteriskPass123!';
CREATE USER 'net2app'@'localhost' IDENTIFIED BY 'Net2appPass123!';
GRANT ALL PRIVILEGES ON asterisk.* TO 'asterisk'@'localhost';
GRANT ALL PRIVILEGES ON net2app.* TO 'net2app'@'localhost';
FLUSH PRIVILEGES;

USE asterisk;
-- Asterisk CDR table
CREATE TABLE IF NOT EXISTS cdr (
  id INT AUTO_INCREMENT PRIMARY KEY,
  calldate DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  clid VARCHAR(80) NOT NULL,
  src VARCHAR(80) NOT NULL,
  dst VARCHAR(80) NOT NULL,
  dcontext VARCHAR(80) NOT NULL,
  channel VARCHAR(80) NOT NULL,
  dstchannel VARCHAR(80) NOT NULL,
  lastapp VARCHAR(80) NOT NULL,
  lastdata VARCHAR(80) NOT NULL,
  duration INT NOT NULL DEFAULT 0,
  billsec INT NOT NULL DEFAULT 0,
  disposition VARCHAR(45) NOT NULL,
  amaflags INT NOT NULL DEFAULT 0,
  accountcode VARCHAR(20) NOT NULL,
  uniqueid VARCHAR(32) NOT NULL,
  userfield VARCHAR(255) NOT NULL,
  INDEX (calldate), INDEX (dst), INDEX (accountcode)
);
EOF`;

const PJSIP_CLIENT = `; /etc/asterisk/pjsip.conf — Add SIP client for Net2app
; Generated by Net2app — VoIP Platform

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; ===== CLIENT: example_client =====
[example_client]
type=endpoint
context=from-clients
disallow=all
allow=ulaw
allow=alaw
allow=g729
aors=example_client
auth=example_client-auth
callerid=Net2app <1000>
max_contacts=30

[example_client-auth]
type=auth
auth_type=userpass
username=example_client
password=SecurePass123

[example_client]
type=aor
max_contacts=30
qualify_frequency=60

; Reload: asterisk -rx "pjsip reload"`;

const FIREWALL = `#!/bin/bash
# Debian 12 Firewall for Net2app VoIP/SMS
ufw allow 22/tcp    # SSH
ufw allow 5060/udp  # SIP
ufw allow 5060/tcp  # SIP TCP
ufw allow 10000:20000/udp  # RTP Media
ufw allow 5038/tcp  # Asterisk AMI
ufw allow 2775/tcp  # SMPP
ufw allow 13013/tcp # Kannel SendSMS
ufw allow 13000/tcp # Kannel Admin
ufw allow 3306/tcp  # MariaDB (local only, restrict in prod)
ufw --force enable
ufw status verbose`;

export default function VoipDeployGuide() {
  const [tab, setTab] = useState("asterisk");

  return (
    <div className="space-y-4">
      <div className="p-4 bg-blue-50 border border-blue-200 rounded-xl flex gap-3">
        <Server className="w-5 h-5 text-blue-600 mt-0.5 shrink-0" />
        <div>
          <p className="text-sm font-semibold text-blue-800">Debian 12 Deployment Guide</p>
          <p className="text-xs text-blue-700 mt-1">
            Full deployment for Net2app on Debian 12 — Asterisk 20+ (Voice), Kannel SMS, MariaDB, SMPP server (client & server mode), firewall rules.
          </p>
        </div>
      </div>

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="flex-wrap h-auto gap-1">
          <TabsTrigger value="asterisk"><Phone className="w-3.5 h-3.5 mr-1" />Asterisk 20</TabsTrigger>
          <TabsTrigger value="kannel"><MessageSquare className="w-3.5 h-3.5 mr-1" />Kannel SMS</TabsTrigger>
          <TabsTrigger value="smpp"><Server className="w-3.5 h-3.5 mr-1" />SMPP</TabsTrigger>
          <TabsTrigger value="db"><Database className="w-3.5 h-3.5 mr-1" />Database</TabsTrigger>
          <TabsTrigger value="pjsip">PJSIP Config</TabsTrigger>
          <TabsTrigger value="firewall"><ShieldCheck className="w-3.5 h-3.5 mr-1" />Firewall</TabsTrigger>
        </TabsList>

        <TabsContent value="asterisk" className="mt-4 space-y-4">
          <div className="flex gap-2 flex-wrap">
            <Badge className="bg-orange-50 text-orange-700 border-orange-200" variant="outline">Asterisk 20+</Badge>
            <Badge className="bg-blue-50 text-blue-700 border-blue-200" variant="outline">Debian 12</Badge>
            <Badge className="bg-green-50 text-green-700 border-green-200" variant="outline">PJSIP</Badge>
            <Badge className="bg-purple-50 text-purple-700 border-purple-200" variant="outline">MariaDB CDR</Badge>
          </div>
          <CodeBlock code={ASTERISK_INSTALL} label="Install Asterisk 20 on Debian 12" />
        </TabsContent>

        <TabsContent value="kannel" className="mt-4">
          <CodeBlock code={KANNEL_INSTALL} label="Install & Configure Kannel SMS Gateway" />
        </TabsContent>

        <TabsContent value="smpp" className="mt-4">
          <CodeBlock code={SMPP_SETUP} label="SMPP Server Setup (Client + Server mode)" />
        </TabsContent>

        <TabsContent value="db" className="mt-4">
          <CodeBlock code={DB_SETUP} label="MariaDB Setup — Asterisk CDR + Net2app database" />
        </TabsContent>

        <TabsContent value="pjsip" className="mt-4">
          <CodeBlock code={PJSIP_CLIENT} label="PJSIP Client Config — /etc/asterisk/pjsip.conf" />
        </TabsContent>

        <TabsContent value="firewall" className="mt-4">
          <CodeBlock code={FIREWALL} label="UFW Firewall Rules — Debian 12" />
        </TabsContent>
      </Tabs>
    </div>
  );
}